[package]
name = "send_email"
version = "0.1.0"
authors = ["zzApotheosis <zzApotheosis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.9.6"
lettre_email = "0.9.4"
