#!/bin/sh

# Define variables
CWD=$(pwd)
SCRIPTDIR=$(dirname $(readlink -f "$0"))
BACKUPDIR=$SCRIPTDIR/backups
INDEXFILE="/var/tmp/mcserverbackupindex.dat"

# Ensure backup directory exists
mkdir -pv $BACKUPDIR
chmod 0775 $BACKUPDIR

# Ensure index file exists
if [[ ! -f $INDEXFILE ]]; then
	echo 0 > $INDEXFILE
fi

# Get index number
let "INDEX=$(cat $INDEXFILE)"

# Perform backup
tar -czvf backup$INDEX.tar.gz --exclude="*database.db*" world world_the_end world_nether plugins server.properties ops.json launch.sh eula.txt

# Move archive to backups directory
mv backup$INDEX.tar.gz $BACKUPDIR

# Remove most backups; keep particular indexes
for (( i = $INDEX - 1; i >= 0; i-- )); do
	if [[ $i -lt $(( INDEX - 25 )) ]]; then
		if [[ -f $BACKUPDIR/backup$i.tar.gz ]]; then
			rm -rv $BACKUPDIR/backup$i.tar.gz
		fi
	elif [[ $(( i % 5 )) -ne 0 ]]; then
		if [[ -f $BACKUPDIR/backup$i.tar.gz ]]; then
			rm -rv $BACKUPDIR/backup$i.tar.gz
		fi
	fi
done

# Increment index
let INDEX++
echo $INDEX > $INDEXFILE

