;; Define variables to use later
(setq-default pkg-installed-company-p nil)
(setq-default pkg-installed-compat-p nil)
(setq-default pkg-installed-dash-p nil)
(setq-default pkg-installed-eglot-p nil)
(setq-default pkg-installed-eldoc-p nil)
(setq-default pkg-installed-erc-p nil)
(setq-default pkg-installed-evil-p nil)
(setq-default pkg-installed-flycheck-p nil)
(setq-default pkg-installed-goto-chg-p nil)
(setq-default pkg-installed-magit-p nil)
(setq-default pkg-installed-multishell-p nil)
(setq-default pkg-installed-neotree-p nil)
(setq-default pkg-installed-org-p nil)
(setq-default pkg-installed-protobuf-p nil)
(setq-default pkg-installed-rust-mode-p nil)
(setq-default pkg-installed-spacemacs-common-p nil)
(setq-default pkg-installed-vertico-p nil)
(setq-default pkg-installed-vterm-p nil)
(setq-default pkg-installed-yasnippet-p nil)
(setq-default pkg-installed-fakepkg-p nil)

(let (
      (pkg-setup-dir (concat user-emacs-directory "/init.d/pkg-setup.d/"))
      (user-pkgs-dir (concat user-emacs-directory "/pkgs/"))
      )
  (load-file (concat pkg-setup-dir "/setup-spacemacs-theme.el"))
  (load-file (concat pkg-setup-dir "/setup-company.el"))
  (load-file (concat pkg-setup-dir "/setup-dash.el"))
  (load-file (concat pkg-setup-dir "/setup-eglot.el"))
  (load-file (concat pkg-setup-dir "/setup-evil.el"))
  (load-file (concat pkg-setup-dir "/setup-flycheck.el"))
  (load-file (concat pkg-setup-dir "/setup-goto-chg.el"))
  (load-file (concat pkg-setup-dir "/setup-magit.el"))
  (load-file (concat pkg-setup-dir "/setup-multishell.el"))
  (load-file (concat pkg-setup-dir "/setup-org.el"))
  (load-file (concat pkg-setup-dir "/setup-rust-mode.el"))
  (load-file (concat pkg-setup-dir "/setup-vertico.el"))
  (load-file (concat pkg-setup-dir "/setup-yasnippet.el"))
  (load-file (concat pkg-setup-dir "/setup-erc.el"))
  (load-file (concat pkg-setup-dir "/setup-eshell.el"))

  ;; Non GNU ELPA packages (generally these are on MELPA but I'd prefer to manage them myself. See emacs-setup.pl)
  (when (or
	 (string-equal system-type "gnu")
	 (string-equal system-type "gnu/linux")
	 (string-equal system-type "darwin")
	 )
    ;; lmao Windows you suuuuuucccccckkkkkk
    (load-file (concat pkg-setup-dir "/setup-vterm.el"))
    )
  (load-file (concat pkg-setup-dir "/setup-neotree.el"))
  (load-file (concat pkg-setup-dir "/setup-protobuf.el"))
  (load-file (concat pkg-setup-dir "/setup-eldoc-box.el"))
  )
