;; Add extra load-path items
;;(add-to-list 'load-path "~/.emacs.d/pkgs/auto-complete")
(let (
      (pkg-setup-dir (concat user-emacs-directory "/init.d/pkg-setup.d/"))
      (user-pkgs-dir (concat user-emacs-directory "/pkgs/"))
      )
  (load-file (concat pkg-setup-dir "/setup-spacemacs-theme.el"))
  (load-file (concat pkg-setup-dir "/setup-company.el"))
  (load-file (concat pkg-setup-dir "/setup-dash.el"))
  (load-file (concat pkg-setup-dir "/setup-eglot.el"))
  (load-file (concat pkg-setup-dir "/setup-evil.el"))
  (load-file (concat pkg-setup-dir "/setup-flycheck.el"))
  (load-file (concat pkg-setup-dir "/setup-goto-chg.el"))
  (load-file (concat pkg-setup-dir "/setup-magit.el"))
  (load-file (concat pkg-setup-dir "/setup-multishell.el"))
  (load-file (concat pkg-setup-dir "/setup-org.el"))
  (load-file (concat pkg-setup-dir "/setup-rust-mode.el"))
  (load-file (concat pkg-setup-dir "/setup-vertico.el"))
  (load-file (concat pkg-setup-dir "/setup-yasnippet.el"))
  (load-file (concat pkg-setup-dir "/setup-erc.el"))

  ;; Non GNU ELPA packages (generally these are on MELPA but I'd prefer to manage them myself. See emacs-setup.pl)
  (when (or
	 (string-equal system-type "gnu")
	 (string-equal system-type "gnu/linux")
	 (string-equal system-type "darwin")
	 )
    ;; lmao Windows you suuuuuucccccckkkkkk
    (load-file (concat pkg-setup-dir "/setup-vterm.el"))
    )
  (load-file (concat pkg-setup-dir "/setup-neotree.el"))
  (load-file (concat pkg-setup-dir "/setup-protobuf.el"))
  (load-file (concat pkg-setup-dir "/setup-eldoc-box.el"))
  )
