#!/bin/sh

if [[ -n $SSH_CLIENT || -n $SSH_TTY || -n $SSH_CONNECTION ]]; then
	echo "WE GOT DA SSH!!!!!"
	echo $SSH_CLIENT
	echo $SSH_TTY
	echo $SSH_CONNECTION
else
	echo "NO SSH!!!!!!!!!!!!!!!!!!!!!!"
fi

