#!/bin/sh

ctrFile="/var/tmp/yeetcounter"

if [ -e $ctrFile ]; then
	count=$(cat $ctrFile)
else
	count=0
fi

((count++))

echo $count > $ctrFile

echo "You have yeeted $count times! YEET YEET BO BEET LUL!!!"

