#!/bin/sh

SCRIPTDIR=$(dirname "$(readlink -f $0)")
PARENTDIR=$(dirname "$SCRIPTDIR") # Use parent directory

# Fetch all the files I want to backup/share to my GitHub repository
# Kitty Terminal Config
if [ -f "$HOME/.config/kitty/kitty.conf" ]; then
	cp -v "$HOME/.config/kitty/kitty.conf" "$PARENTDIR/System Config"
fi

# Global Zsh Init
if [ -f "/etc/zsh/zshrc" ]; then
	cp -v "/etc/zsh/zshrc" "$PARENTDIR/System Config/etc.zsh.zshrc"
fi

# Zsh Environment
if [ -f "$HOME/.zshenv" ]; then
	cp -v "$HOME/.zshenv" "$PARENTDIR/System Config"
fi

# Zsh Init
if [ -f "$HOME/.zshrc" ]; then
	cp -v "$HOME/.zshrc" "$PARENTDIR/System Config"
fi

# Minecraft Server Backup Script
if [ -f "/home/mcadmin/MCJEServer/backup" ]; then
	cp -v "/home/mcadmin/MCJEServer/backup" "$SCRIPTDIR/mcserver"
fi

# Minecraft Server Restore Script
if [ -f "/home/mcadmin/MCJEServer/restore" ]; then
	cp -v "/home/mcadmin/MCJEServer/restore" "$SCRIPTDIR/mcserver"
fi

# SSHD Config
if [ -f "/etc/ssh/sshd_config" ]; then
	cp -v "/etc/ssh/sshd_config" "$PARENTDIR/System Config/etc.ssh.sshd_config"
fi

# User bin directory
if [ -d "/home/zzapotheosis/bin" ]; then
	rm -rv "$SCRIPTDIR/bin"
	mkdir -v "$SCRIPTDIR/bin"

	# Fetch dailyupdate script for root "hourly" crontab
	if [ -f "/home/zzapotheosis/bin/dailyupdate" ]; then
		cp -rv "/home/zzapotheosis/bin/dailyupdate" "$SCRIPTDIR/bin"
	fi

	# yeet script
	if [ -f "/home/zzapotheosis/bin/yeet" ]; then
		cp -rv "/home/zzapotheosis/bin/yeet" "$SCRIPTDIR/bin"
	fi

	# gacp script
	if [ -f "/home/zzapotheosis/bin/gacp" ]; then
		cp -rv "/home/zzapotheosis/bin/gacp" "$SCRIPTDIR/bin"
	fi

	# zzCrypt script
	if [ -f "/home/zzapotheosis/bin/zzCrypt" ]; then
		cp -rv "/home/zzapotheosis/bin/zzCrypt" "$SCRIPTDIR/bin"
	fi
fi

