#!/bin/sh

# Fetch all the files I want to backup/share to my GitHub repository
if [[ -f "$HOME/.config/kitty/kitty.conf" ]]; then
	cp -v "$HOME/.config/kitty/kitty.conf" ../Config
fi

if [[ -f "/etc/zsh/zshrc" ]]; then
	cp -v "/etc/zsh/zshrc" "../Config/etc.zsh.zshrc"
fi

if [[ -f "$HOME/.zshenv" ]]; then
	cp -v "$HOME/.zshenv" ../Config
fi

if [[ -f "$HOME/.zshrc" ]]; then
	cp -v "$HOME/.zshrc" ../Config
fi

if [[ -f "/home/mcadmin/MCJEServer/backup" ]]; then
	cp -v "/home/mcadmin/MCJEServer/backup" "../../Shell Scripts/mcserver"
fi

if [[ -f "/home/mcadmin/MCJEServer/restore" ]]; then
	cp -v "/home/mcadmin/MCJEServer/restore" "../../Shell Scripts/mcserver"
fi

