#!/bin/sh

# Fetch all the files I want to backup/share to my GitHub repository
if [[ -f "$HOME/.config/kitty/kitty.conf" ]]; then
	cp "$HOME/.config/kitty/kitty.conf" ../Config
	echo "Copied ~/.config/kitty/kitty.conf"
fi

if [[ -f "/etc/zsh/zshrc" ]]; then
	cp "/etc/zsh/zshrc" "../Config/etc.zsh.zshrc"
	echo "Copied /etc/zsh/zshrc"
fi

if [[ -f "$HOME/.zshenv" ]]; then
	cp "$HOME/.zshenv" ../Config
	echo "Copied ~/.zshenv"
fi

if [[ -f "$HOME/.zshrc" ]]; then
	cp "$HOME/.zshrc" ../Config
	echo "Copied ~/.zshrc"
fi
