[package]
name = "rlib-exec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.rlib]
path = "../rlib"

# This also works
#[dependencies]
#rlib = { path = "../rlib" }
